import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import CustomLink from '../components/Link'
import LangSwitter from '../components/LangSwitter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <nav>
          {/* @ts-ignore */}
          <CustomLink href='/' locale={false}>Home</CustomLink><br/>
            {/* @ts-ignore */}
          <CustomLink href='/posts' locale={false}>Posts</CustomLink>
        </nav>
        <LangSwitter/>
      </body>
    </html>
  )
}
